import { createApp } from 'vue';
import App from './App.vue';
import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// import TUICallKit
import { TUICallKit } from '@tencentcloud/call-uikit-vue';
import router from './router';


const SDKAppID = 1400034652; // Your SDKAppID
const secretKey = '90a459de733e7fa5c3f48b09baa012f52f846e0789ca6a2bf7af984ae17764b6'; //Your secretKey
const userID = 'ligeng'; // User ID


// init TUIKit
const TUIKit = TUICore.init({
    SDKAppID,
});
// TUIKit add TUIComponents
TUIKit.use(TUIComponents);
// TUIKit add TUICallKit
TUIKit.use(TUICallKit);


// login TUIKit
TUIKit.login({
    userID: userID,
    userSig: genTestUserSig({
        SDKAppID,
        secretKey,
        userID,
    }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
});


createApp(App)
    .use(TUIKit)
    .use(router)
    .mount('#app');

